models/city.py
class City:

      def __init__(self, name, country, visited = False, id = None):
            self.name = name
            self.country = country
            self.visited = visited          
            self.id = id

      def mark_visited(self):
            self.visited = True

models/country.py
class Country:

      def __init__(self, name, id = None):
            self.name = name
            self.id = id

      

models/user.py
class User:

    def __init__(self, name, id = None):
      self.name = name
      self.id = id

app.py
from flask import Flask, render_template, request, redirect
from controllers.cities_controller import cities_blueprint
from controllers.countries_controller import countries_blueprint




app = Flask(__name__)

app.register_blueprint(cities_blueprint)
app.register_blueprint(countries_blueprint)



@app.route("/")
def main():
    return render_template('index.html')

if __name__ == '__main__':
    app.run()

controllers/cities_controller.py
from flask import Flask, render_template, request, redirect
from repositories import country_repository
from repositories import city_repository

from models.country import Country
from models.city import City

from flask import Blueprint

cities_blueprint = Blueprint("cities", __name__)


@cities_blueprint.route("/cities")
def cities ():
    cities = city_repository.select_all() # NEW
    return render_template("cities/index.html", all_cities = cities)

# NEW
# GET '/cities/new'
@cities_blueprint.route("/cities/new", methods=['GET'])
def new_city():
    countries = country_repository.select_all()
    return render_template("/cities/new.html", all_countries = countries)



# CREATE
# POST '/cities
@cities_blueprint.route("/cities",  methods=['POST'])
def create_city():
    city_name  = request.form['city']
    country = country_repository.select(request.form['country_id'])
    city = City(city_name, country)
    city_repository.save(city)
    return redirect('/cities')


    #show

@cities_blueprint.route("/cities/<id>", methods=['GET'])
def show_city(id):
    city = city_repository.select(id)
    return render_template('cities/show.html', city = city)

    #EDIT get 

@cities_blueprint.route("/cities/<id>/edit", methods=['GET'])
def edit_city(id):
    city = city_repository.select(id)
    country = country_repository.select_all()
    return render_template('cities/edit.html', city = city, all_countries = country)




    #UPDATE put


@cities_blueprint.route("/cities/<id>", methods=['POST'])
def update_city(id):
    city_name  = request.form['city']
    country = country_repository.select(request.form['country_id'])
    city = City(city_name, country,request.form['visited'],id)
    city_repository.update(city)
    return redirect('/cities')


    #DELETE

@cities_blueprint.route("/cities/<id>/delete", methods=['POST'])
def delete_city(id):
    city_repository.delete(id)
    return redirect('/cities')

   

controllers/countries_controller.py
from flask import Flask, render_template, request, redirect
from repositories import country_repository
from repositories import city_repository

from models.country import Country
from models.city import City

from flask import Blueprint

countries_blueprint = Blueprint("countries", __name__)


@countries_blueprint.route("/countries")
def countries ():
    countries= country_repository.select_all() 
    return render_template("countries/index.html", all_countries = countries)

# NEW
# GET '/countries/new'
@countries_blueprint.route("/countries/new", methods=['GET'])
def new_country():
    countries = country_repository.select_all()
    return render_template("/countries/new.html", all_countries = countries)



# CREATE
# POST '/countries
@countries_blueprint.route("/countries",  methods=['POST'])
def create_country ():
    country_name  = request.form['country']
    country = Country(country_name)
    country_repository.save(country)
    return redirect('/countries')

  #show

@countries_blueprint.route("/countries/<id>", methods=['GET'])
def show_country(id):
    Country = country_repository.select(id)
    return render_template('countries/show.html', country = Country)

    #EDIT get 

@countries_blueprint.route("/countries/<id>/edit", methods=['GET'])
def edit_country(id):
    country = country_repository.select(id)
    return render_template('countries/edit.html', country = country)




    #UPDATE put


@countries_blueprint.route("/countries/<id>", methods=['POST'])
def update_country(id):
    country = Country(request.form['country'],id )
    country_repository.update(country)
    return redirect('/countries')


    #DELETE

@countries_blueprint.route("/countries/<id>/delete", methods=['POST'])
def delete_country(id):
    country_repository.delete(id)
    return redirect('/countries')

controllers/destination_controller.py
from flask import Flask, render_template, request, redirect
from repositories import country_repository
from repositories import city_repository

from models.country import Country
from models.city import City

from flask import Blueprint

destinations_blueprint = Blueprint("destinations", __name__)


@destinations_blueprint.route("/destinations")
def cities ():
    cities = city_repository.select_all() # NEW
    return render_template("destinations/index.html", all_cities = cities)

# NEW
# GET '/destinations/new'
@destinations_blueprint.route("/destinations/new", methods=['GET'])
def countries():
    countries = country_repository.select_all()
    return render_template("destinations/new.html", all_countries = countries)



# CREATE
# POST '/destinations'
@destinations_blueprint.route("/destinations",  methods=['POST'])
def create_city():
    city_name  = request.form['city']
    country = country_repository.select(request.form['country_id'])
    city = City(name, country , visited)
    city_repository.save(city)
    return redirect('/destinations')

templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>My Travel Bucket List</title>

<link rel="stylesheet" href="{{ url_for('static', filename='style.css') }}"
</head>
<body>
  <header>
    <nav>
      <ul class="menu">
       <li><a href="/">Home</a></li>
        <li><a href="{{ url_for('cities.cities') }}">Cities</a></li>
        <li><a href="{{ url_for('countries.countries') }}">Countries </a></li>
      </ul>
    </nav>
  </header>
  <div class="container">
    {% block content %}
    {% endblock %}
  </div>

</body>
</html>

templates/cities/edit.html
{% extends "base.html" %}
{% block content %}

<form action="/cities/{{city.id}}" method="post">
  

    <h2>Update city</h2>

<form action="/cities/" method="post">

 
    <label for="city">City:</label>
    <input type="text" id="city" name="city" value="{{city.name}}" required>
  


  
    <label for="country">Country</label>
    <select  name="country_id" id="country">
      {% for country in all_countries %}
        <option value="{{ country.id }}" {% if country.id == city.country.id %} selected {% endif %}>
        {{ country.name }}
      </option>
        {% endfor %}
      </select>
 

      <label for="visited">Have you visited yet?</label>
      <select name="visited" id="visited">
        <option value="True" {% if city.visited == True %} selected {% endif %}>Yes</option>
        <option value="False" {% if city.visited == False %} selected {% endif %}>No</option>




      </select>





    </div class= "buttons">
  <button type="submit">Update City</button>
</div>
</form>

{% endblock %}

templates/cities/index.html
{% extends "base.html" %}
{% block content %}

<h2>Here are the list of cities on my bucket list:</h2>
<h3>Click on a city to update</h3>

<!-- <h3><a href="/cities/new">Add a new city to List</a></h3> -->
<div class="buttons">
<form action="/cities/new">
<input type="submit" value="add new city">
</form>

</div>
<br>
<br>

<table>
  <tr>
    <th>City</th>
    
    <th>Country</th>
    
    <th>Visited?</th>
    <th>Delete</th>
  </tr>
  {% for city in all_cities %}
  <tr>
    <td><a href="/cities/{{city.id}}">{{city.name}}</a></td>

    <td>{{city.country.name}}</td>
    <td>
      {% if city.visited == True %}
      <span> &#9989;</span>
      {% else %}
      <span> &#x274C; </span>

      {% endif %}

    </td>
    <td>
    </div class= "buttons">
      <form action="/cities/{{ city.id }}/delete" method="POST">
        <input type="submit" value="delete" />
      </form>
      </div>
    </td>
  </tr>



  </div>
  {% endfor %}

</table>

{% endblock %}

templates/cities/new.html
{% extends "base.html" %}
{% block content %}

<h2>Add a new city to your bucket list</h2>

<form action="/cities" method="post">

  <div>
    <label for="city">City:</label>
    <input type="text" id="city" name="city" placeholder="City" required autofocus>
  </div>



  <div>
    <label for="country">Country</label>
    <select id="country" name="country_id">
      {% for country in all_countries %}
        <option value="{{ country.id }}">{{ country.name }}</option>
      {% endfor %}
    </select>
  </div>
</div class= "buttons">
  <button type="submit">Add City</button>
</div>
</form>

{% endblock %}

templates/cities/old index.html
{% extends "base.html" %}
{% block content %}

<h2>Here is the list of Cities on my Bucket List:</h2>
<h3>Click on the city to update</h3>

<h3><a href="/cities/new">Add a new city to List</a></h3>




{% for city in all_cities %}
  <div class="city">
    <a href="/cities/{{city.id}}">{{city.name}}</a>
   
      
        {{city.country.name}}
  
  <p>City has been visited</p>
{% if city.visited == True %}
      <span> &#9989;</span>
      {% else %} 
      <span> &#x274C; </span>

      {% endif %}

  <p>
    <form action="/cities/{{ city.id }}/delete" method="POST">
      <input type="submit" value="delete" />
    </form>
  </p>

  </div>
{% endfor %}



{% endblock %}

templates/cities/show.html
{% extends "base.html" %}
{% block content %}

  <div>
    <p>City: {{city.name}}</p>
    <hr>
    <p>Country: {{city.country.name}}</p>
    
    <p><a href="/cities/{{city.id}}/edit">Edit</a></p>
  </div>

{% endblock %}

templates/countries/edit.html
{% extends "base.html" %}
{% block content %}

<form action="/countries/{{country.id}}" method="post">
  

    <h2>Update Country</h2>

<form action="/countries/" method="post">

  <div>
    <label for="country">Country:</label>
    <input type="text" id="country" name="country" value="{{country.name}}" required>
  </div>


  <div class="buttons">
  <button type="submit">Update Country</button>
</div>
</form>

{% endblock %}

templates/countries/index.html
{% extends "base.html" %}
{% block content %}

<h2>Here is the list of Countries on my Bucket List:</h2>
<h3>Click on the Country to update</h3>
<!-- <h3><a href="/countries/new">Add a new country to List</a></h3> -->

<div class="buttons">
  <form action="/countries/new">
  <input type="submit" value="add new country">
  </form>
  
  </div>

<table>
<tr>
<th>Country name</th>

<th>Delete</th>

</tr>
{% for country in all_countries %}

<tr>


<td>
  <div class="country">
      <a href="/countries/{{country.id}}">{{country.name}}</a>
  </div>
</td>

<td>
  <div>
  </div class= "buttons">
    <form action="/countries/{{ country.id }}/delete" method="POST">
      <input type="submit" value="delete" />
    </form>
  </div>
  
</td>

</tr>

{% endfor %}

</table>


{% endblock %}

templates/countries/new.html
{% extends "base.html" %}
{% block content %}

<h2>Add a new country to your bucket list</h2>

<form action="/countries" method="post">

  <div>
    <label for="country">Country:</label>
    <input type="text" id="country" name="country" placeholder="Country" required autofocus>
  </div>

</div class= "buttons">
  <button type="submit">Add Country</button>
</div>
</form>

{% endblock %}

templates/countries/show.html
{% extends "base.html" %}
{% block content %}

  <div>
  
    <p>Country: {{country.name}}</p>
    
    <p><a href="/countries/{{country.id}}/edit">Edit</a></p>
  </div>

{% endblock %}

templates/index.html
{% extends "base.html" %}
{% block content %}
<h1>Welcome to the Travel Bucket List!</h1>
<section id="home-image">


</section>
{% endblock %}

templates/visits/new.html
{% extends "base.html" %}
{% block content %}

<form action="/visits" method="post">

  <div>
    <label for="city">City:</label>
    <input type="text" id="city" name="city" placeholder="City" required autofocus>
  </div>


  <div>
    <label for="country">Country</label>
    <select id="country" name="country_id">
      {% for country in all_countries %}
        <option value="{{ country.id }}">{{ country.name }}</option>
      {% endfor %}
    </select>
  </div>

  <button type="submit">Add Destination</button>

</form>

{% endblock %}